// src/components/gameSetup/Waiting.vue
<script lang="ts">
import { Socket } from 'socket.io-client'
import { ref, defineComponent, PropType, inject } from 'vue'
import PlayerCard from './PlayerCard.vue'
import { IPlayer, IHostSetting } from '~/types'
export default defineComponent({
  components: {
    PlayerCard,
  },
  props: {
    jkey: { type: String, default: '' },
    isHost: { type: Boolean, default: false },
    players: { type: Array as PropType<Array<IPlayer>>, required: true },
    hostSettings: { type: Object as PropType<IHostSetting>, required: true },
  },
  setup(props, { emit }) {
    const socket: Socket = inject('socket')!
    const copyKey = () => {
      navigator.clipboard.writeText(props.jkey)
    }
    const winAmount = ref(props.hostSettings.winAmount)
    const enableWise = ref(props.hostSettings.enableWise)
    const settingChanged = () => {
      socket.emit('settingChanged', { winAmount: winAmount.value, enableWise: enableWise.value })
    }
    socket.on('newSettings', (settings) => {
      winAmount.value = settings.winAmount
      enableWise.value = settings.enableWise
    })
    return {
      copyKey, winAmount, enableWise, settingChanged,
    }
  },
})

</script>
<template>
  <div class="w-3/4 mx-auto py-16 h-full flex flex-col justify-between items-center">
    <div class="grid grid-cols-2 grid-rows-2 gap-4">
      <span class="text-3xl mr-6">Gwinnpunktzahl</span>
      <input
        v-model="winAmount"
        :disabled="!isHost"
        class="mt-0 block px-0.5 text-darker text-xl text-center border-0 focus:ring-0 focus:border-white"
        @change="settingChanged"
      />
      <label for="checkbox" class="text-3xl mr-6">Wise isch erloubt</label>
      <input
        id="checkbox"
        v-model="enableWise"
        :disabled="!isHost"
        type="checkbox"
        class="h-6 w-6 bg-white block appearance-none justify-self-center checked:bg-highlight"
        @change="settingChanged"
      />
    </div>
    <div class="grid grid-cols-4 gap-12">
      <PlayerCard v-for="p in players" :key="p.id" :player="p" />
      <div v-for="n in 4 - players.length" :key="n" class="flex flex-col items-center">
        <div class="mb-5 flex-grow bg-white w-full rounded-full"></div>
        <div>Läär</div>
      </div>
    </div>
    <div v-if="isHost" class="flex justify-between w-full items-center">
      <div>
        <button
          class="px-8 py-3 text-2xl text-white tracking-widest bg-accent hover:bg-skylight uppercase"
          @click="copyKey"
        >Iladig kopiere</button>
      </div>
      <a
        class="pointer heroButton px-8 py-3 text-2xl text-white relative tracking-widest bg-highlight uppercase"
      >
        <span class="heroButtonOverlay"></span>
        <span class="label relative z-10">Starte</span>
      </a>
    </div>
  </div>
</template>

// components/game/setupState/waiting.tsx
import React from "react";
import { HostSetting, Player } from "./lobby";
import PlayerCard from "./playercard";

type Props = {
  hostSettings: HostSetting;
  players: Player[];
  isHost: boolean;
  joinKey: string;
};
type State = {};
class Waiting extends React.Component<Props, State> {
  state: State = {
    setupComplete: false,
  };
  playerList() {
    return this.props.players.map((p) => <PlayerCard key={p.id} player={p} />);
  }
  openSpots() {
    let rm = 4 - this.props.players.length;
    let r = [];
    for (let index = 0; index < rm; index++) {
      r.push(
        <div key={index} className="flex flex-col items-center">
          <div className="mb-5 flex-grow bg-white w-full rounded-full"></div>
          <div>Läär</div>
        </div>
      );
    }
    return r;
  }
  render() {
    return (
      <div
        className={`w-3/4 mx-auto py-16 h-full flex flex-col justify-between items-center`}
      >
        <div className="">
          <div>Settings 1</div>
          <div>Settings 1</div>
          <div>Settings 1</div>
          <div>Settings 1</div>
        </div>
        <div className="grid grid-cols-4 gap-12">
          {this.playerList()}
          {this.openSpots()}
        </div>
        {this.props.isHost && (
          <div className="flex justify-between w-full items-center">
            <div>
              <button className="px-8 py-3 text-2xl text-white tracking-widest bg-theme-accent hover:bg-theme-skylight uppercase"
                onClick={() => { navigator.clipboard.writeText(this.props.joinKey); }}>
                Iladig kopiere
            </button>
            </div>
            <a
              className={`pointer heroButton px-8 py-3 text-2xl text-white relative tracking-widest bg-theme-highlight uppercase`}
            >
              <span className="heroButtonOverlay"></span>
              <span className="label relative z-10">Starte</span>
            </a>

          </div>
        )}
      </div>
    );
  }
}

export default Waiting;
