// components/game/setupState/lobby.tsx
import React from "react";
import Waiting from "./waiting";
import Character from "./character";
import socket from "../../..//lib/socket";

interface MyProps {
  jkey: string;
}

export enum PlayerColor {
  BLUE = "#abe2f5",
  RED = "#F73859",
}
export type HostSetting = {
  winAmount: number;
  enableWise: boolean;
};
export type Player = {
  self: boolean;
  id: string;
  name: string;
  teamRed: boolean;
};

type State = {
  setupComplete: boolean;
  clientIsHost: boolean;
  hostSettings: HostSetting;
  players: Player[];
  joinKey: string;
  nameInput: string;
};

class Lobby extends React.Component<MyProps, State> {
  state: State = {
    setupComplete: false,
    clientIsHost: false,
    joinKey: "",
    nameInput: "",
    hostSettings: {
      winAmount: 1000,
      enableWise: true,
    },
    players: [],
  };
  constructor(props: MyProps) {
    super(props);
    this.state.joinKey = props.jkey;
  }
  handleHost = (myName: string) => {
    this.setState({
      clientIsHost: true,
      nameInput: myName,
    });
    this.serverConnect(myName, true, "");
  };
  handleJoin = (myName: string, key: string) => {
    if (key) {
      this.setState({
        nameInput: myName,
      });
      this.serverConnect(myName, false, key);
      return;
    }
    return;
  };
  renderCharacter() {
    return (
      <Character
        jKey={this.state.joinKey}
        onHost={this.handleHost}
        onJoin={this.handleJoin}
      />
    );
  }
  renderWaiting() {
    return (
      <Waiting
        joinKey={this.state.joinKey}
        isHost={this.state.clientIsHost}
        players={this.state.players}
        hostSettings={this.state.hostSettings}
      />
    );
  }
  charReady() {
    if (!this.state.setupComplete) return this.renderCharacter();
    return this.renderWaiting();
  }
  render() {
    return (
      <div className="flex items-center h-full relative">
        <div className="absolute w-16 h-16 bg-theme-contrast top-20"></div>
        <div className="absolute w-16 h-16 bg-theme-deep right-0 top-80"></div>
        <div className="absolute w-16 h-16 bg-theme-contrast bottom-80"></div>
        <div className="absolute w-16 h-16 bg-theme-deep right-0 bottom-20"></div>
        <div
          className="container bg-theme-dark text-white h-4/5 mx-auto"
          style={{ borderRadius: "40px" }}
        >
          {this.charReady()}
        </div>
      </div>
    );
  }
  serverConnect(username: string, host: boolean, key: string) {
    socket.auth = { username, host, key };
    socket.connect();
  }
  componentDidMount() {
    socket.on("hosted", (key: string) => {
      this.setState({
        joinKey: window.location.origin + "/game?key=" + key,
        setupComplete: true
      });
    });
    socket.on("players", (players) => {
      let newPlayers: Player[] = this.state.players.concat(
        players.map((p: { id: any; name: any; }, i: number) => {
          return {
            self: p.id == p.id,
            id: p.id,
            name: p.name,
            teamRed: i > 1,
          }
        })
      )
      this.setState({
        players: newPlayers,
      });
    });
    socket.on("connect_error", (err) => {
      if (err.message === "invalid username") {
        this.setState({
          nameInput: "",
          players: []
        });
      }
    });
  }
}

export default Lobby;

// src/components/gameSetup/Lobby.vue
<script lang="ts">
import { Socket } from 'socket.io-client'
import { ref, defineComponent, inject, onBeforeMount } from 'vue'
import Entry from './Entry.vue'
import Waiting from './Waiting.vue'
import { IPlayer, IHostSetting } from '~/types'

export default defineComponent({
  components: {
    Entry, Waiting,
  },
  props: {
    jkey: { type: String, default: '' },
  },
  setup(props) {
    const clientIsHost = ref(false)
    const joinKey = ref('')
    const nameInput = ref('')
    const p: IPlayer[] = []
    const players = ref(p)
    const hostSettings = ref<IHostSetting>({
      winAmount: 1000,
      enableWise: true,
    })
    const socket: Socket = inject('socket')!
    const setupComplete = ref(false)
    onBeforeMount(() => { if (props.jkey) joinKey.value = props.jkey })
    // onMounted(() => { mounted = true })
    // onBeforeUnmount(() => { mounted = false })
    const serverConnect = (username: string, host: boolean, key: string) => {
      socket.auth = { username, host, key }
      socket.connect()
    }
    const onHost = (name: string) => {
      clientIsHost.value = true
      nameInput.value = name
      serverConnect(name, clientIsHost.value, '')
    }
    const onJoin = (name: string) => {
      if (joinKey.value) {
        nameInput.value = name
        console.log(`name: ${name}`)
        serverConnect(name, false, joinKey.value)
      }
    }
    socket.on('hosted', (key: string) => {
      joinKey.value = `${window.location.origin}/game?key=${key}`
      socket.emit('settingChanged', { winAmount: hostSettings.value.winAmount, enableWise: hostSettings.value.enableWise })
    })
    socket.on('players', (sp) => {
      const newPlayers = sp.map((p: { id: any; name: any; isHost: any }, i: number) => {
        return {
          self: socket.id === p.id,
          isHost: p.isHost,
          id: p.id,
          name: p.name,
          teamRed: i > 1,
        }
      })
      players.value = newPlayers
      setupComplete.value = true
    })
    socket.on('initialSettings', (settings) => {
      hostSettings.value.winAmount = settings.winAmount
      hostSettings.value.enableWise = settings.enableWise
    })
    socket.on('abandoned', () => {
      nameInput.value = ''
      players.value = []
      joinKey.value = ''
      setupComplete.value = false
    })
    socket.on('connect_error', (err) => {
      if (err.message === 'invalid username') {
        nameInput.value = ''
        players.value = []
      }
    })
    return {
      joinKey, nameInput, players, setupComplete, onHost, onJoin, clientIsHost, hostSettings,
    }
  },
})
</script>

<template>
  <div class="flex items-center h-full relative">
    <div class="absolute w-16 h-16 bg-contrast top-20"></div>
    <div class="absolute w-16 h-16 bg-deep right-0 top-80"></div>
    <div class="absolute w-16 h-16 bg-contrast bottom-80"></div>
    <div class="absolute w-16 h-16 bg-deep right-0 bottom-20"></div>
    <div class="container bg-dark text-white h-4/5 mx-auto" :style="{ borderRadius: '40px' }">
      <Entry v-if="!setupComplete" :jkey="joinKey" @host="onHost" @join="onJoin" />
      <Waiting
        v-else
        :is-host="clientIsHost"
        :jkey="joinKey"
        :players="players"
        :host-settings="hostSettings"
      />
    </div>
  </div>
</template>
